/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mochila.genetica;

import mochila.genetica.genetic.population.Population;
import mochila.genetica.genetic.population.PopulationInstance;
import mochila.genetica.genetic.chromosome.ChromosomeContextInstance;
import mochila.genetica.genetic.chromosome.ChromosomeContextInstanceImpl;

import java.util.Scanner;

public class App {
   private static Scanner sc = new Scanner(System.in);

   private static ChromosomeContextInstance getChromosomeValuesFromInputUser(){
       int tam = sc.nextInt();
       int capacity = sc.nextInt();

       int values[] = new int[tam];
       int weight[] = new int[tam];

       for(int i = 0; i<tam; i++){
           values[i] = sc.nextInt();
           weight[i] = sc.nextInt();
       }

       ChromosomeContextInstance chromosomeValues = ChromosomeContextInstanceImpl.fromOfValueAndWeigthAndCapacity(values, weight, capacity);

       return chromosomeValues;
   }
    public static void main(String[] args) {
        ChromosomeContextInstance chromosomeValues = getChromosomeValuesFromInputUser();
        PopulationInstance populationInstance = Population.initializePopulationFromChromosomeValuesAndNumberIndividuals(chromosomeValues, 100);

        int numeroGeracao = 0;

        while(numeroGeracao<50){
            numeroGeracao++;

            populationInstance.sortIndividualsByFitnessFunction();
            if(numeroGeracao>1){
                populationInstance.mataTudoTaOk();
            }
            System.out.println("CROSSOVER("+numeroGeracao+")");
            System.out.println("size: pre crossover:"+populationInstance.size());
            populationInstance.crossover();
            System.out.println("size pos crossover: "+populationInstance.size());
            populationInstance.sortIndividualsByFitnessFunction();
        }




        populationInstance.show();
    }
}
